//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LoyaltyJsonService", ConfigurationName="DenService.LoyaltyJsonService_Port")]
    public interface LoyaltyJsonService_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/LoyaltyJsonService:GetJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<DenService.GetJSON_Result> GetJSONAsync(DenService.GetJSON request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJSON", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LoyaltyJsonService", IsWrapped=true)]
    public partial class GetJSON
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LoyaltyJsonService", Order=0)]
        public string requestName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LoyaltyJsonService", Order=1)]
        public string requestParams;
        
        public GetJSON()
        {
        }
        
        public GetJSON(string requestName, string requestParams)
        {
            this.requestName = requestName;
            this.requestParams = requestParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJSON_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/LoyaltyJsonService", IsWrapped=true)]
    public partial class GetJSON_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/LoyaltyJsonService", Order=0)]
        public string return_value;
        
        public GetJSON_Result()
        {
        }
        
        public GetJSON_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface LoyaltyJsonService_PortChannel : DenService.LoyaltyJsonService_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class LoyaltyJsonService_PortClient : System.ServiceModel.ClientBase<DenService.LoyaltyJsonService_Port>, DenService.LoyaltyJsonService_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LoyaltyJsonService_PortClient() : 
                base(LoyaltyJsonService_PortClient.GetDefaultBinding(), LoyaltyJsonService_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.LoyaltyJsonService_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoyaltyJsonService_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(LoyaltyJsonService_PortClient.GetBindingForEndpoint(endpointConfiguration), LoyaltyJsonService_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoyaltyJsonService_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LoyaltyJsonService_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoyaltyJsonService_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LoyaltyJsonService_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoyaltyJsonService_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DenService.GetJSON_Result> DenService.LoyaltyJsonService_Port.GetJSONAsync(DenService.GetJSON request)
        {
            return base.Channel.GetJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<DenService.GetJSON_Result> GetJSONAsync(string requestName, string requestParams)
        {
            DenService.GetJSON inValue = new DenService.GetJSON();
            inValue.requestName = requestName;
            inValue.requestParams = requestParams;
            return ((DenService.LoyaltyJsonService_Port)(this)).GetJSONAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoyaltyJsonService_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoyaltyJsonService_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://us-proj-app-01.navondemand.us:7107/DEV_USERPASSWORD/WS/CRONUS Cultivation" +
                        "/Codeunit/LoyaltyJsonService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LoyaltyJsonService_PortClient.GetBindingForEndpoint(EndpointConfiguration.LoyaltyJsonService_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LoyaltyJsonService_PortClient.GetEndpointAddress(EndpointConfiguration.LoyaltyJsonService_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            LoyaltyJsonService_Port,
        }
    }
}
