//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVAccess
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", ConfigurationName="NAVAccess.RetailWebServices_Port")]
    public interface RetailWebServices_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices:WebRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVAccess.WebRequest_Result> WebRequestAsync(NAVAccess.WebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices:CreateResponseCode", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVAccess.CreateResponseCode_Result> CreateResponseCodeAsync(NAVAccess.CreateResponseCode request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices:GetPosImage", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVAccess.GetPosImage_Result> GetPosImageAsync(NAVAccess.GetPosImage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices:GetPosHtml", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVAccess.GetPosHtml_Result> GetPosHtmlAsync(NAVAccess.GetPosHtml request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices:IsOnline", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVAccess.IsOnline_Result> IsOnlineAsync(NAVAccess.IsOnline request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices:FillDataSet", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVAccess.FillDataSet_Result> FillDataSetAsync(NAVAccess.FillDataSet request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices:Find", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVAccess.Find_Result> FindAsync(NAVAccess.Find request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices:CreateRecordZoomData", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVAccess.CreateRecordZoomData_Result> CreateRecordZoomDataAsync(NAVAccess.CreateRecordZoomData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices:ValidateRecordZoomInput" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVAccess.ValidateRecordZoomInput_Result> ValidateRecordZoomInputAsync(NAVAccess.ValidateRecordZoomInput request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices:ImportRecordZoomData", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVAccess.ImportRecordZoomData_Result> ImportRecordZoomDataAsync(NAVAccess.ImportRecordZoomData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices:InsertRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVAccess.InsertRecord_Result> InsertRecordAsync(NAVAccess.InsertRecord request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices:DeleteRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVAccess.DeleteRecord_Result> DeleteRecordAsync(NAVAccess.DeleteRecord request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices:WriteRequestLog", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVAccess.WriteRequestLog_Result> WriteRequestLogAsync(NAVAccess.WriteRequestLog request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices:Search", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVAccess.Search_Result> SearchAsync(NAVAccess.Search request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebRequest", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.WebRequestBody Body;
        
        public WebRequest()
        {
        }
        
        public WebRequest(NAVAccess.WebRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class WebRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pxmlRequest;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pxmlResponse;
        
        public WebRequestBody()
        {
        }
        
        public WebRequestBody(string pxmlRequest, string pxmlResponse)
        {
            this.pxmlRequest = pxmlRequest;
            this.pxmlResponse = pxmlResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebRequest_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebRequest_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.WebRequest_ResultBody Body;
        
        public WebRequest_Result()
        {
        }
        
        public WebRequest_Result(NAVAccess.WebRequest_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class WebRequest_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pxmlRequest;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pxmlResponse;
        
        public WebRequest_ResultBody()
        {
        }
        
        public WebRequest_ResultBody(string pxmlRequest, string pxmlResponse)
        {
            this.pxmlRequest = pxmlRequest;
            this.pxmlResponse = pxmlResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResponseCode
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateResponseCode", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.CreateResponseCodeBody Body;
        
        public CreateResponseCode()
        {
        }
        
        public CreateResponseCode(NAVAccess.CreateResponseCodeBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class CreateResponseCodeBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pResponse_Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pResponse_Text;
        
        public CreateResponseCodeBody()
        {
        }
        
        public CreateResponseCodeBody(string pResponse_Code, string pResponse_Text)
        {
            this.pResponse_Code = pResponse_Code;
            this.pResponse_Text = pResponse_Text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResponseCode_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateResponseCode_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.CreateResponseCode_ResultBody Body;
        
        public CreateResponseCode_Result()
        {
        }
        
        public CreateResponseCode_Result(NAVAccess.CreateResponseCode_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class CreateResponseCode_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pResponse_Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pResponse_Text;
        
        public CreateResponseCode_ResultBody()
        {
        }
        
        public CreateResponseCode_ResultBody(string pResponse_Code, string pResponse_Text)
        {
            this.pResponse_Code = pResponse_Code;
            this.pResponse_Text = pResponse_Text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPosImage
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosImage", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.GetPosImageBody Body;
        
        public GetPosImage()
        {
        }
        
        public GetPosImage(NAVAccess.GetPosImageBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class GetPosImageBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recordID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int fieldNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string imageBase64String;
        
        public GetPosImageBody()
        {
        }
        
        public GetPosImageBody(string recordID, int fieldNo, string imageBase64String)
        {
            this.recordID = recordID;
            this.fieldNo = fieldNo;
            this.imageBase64String = imageBase64String;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPosImage_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosImage_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.GetPosImage_ResultBody Body;
        
        public GetPosImage_Result()
        {
        }
        
        public GetPosImage_Result(NAVAccess.GetPosImage_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class GetPosImage_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool return_value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string imageBase64String;
        
        public GetPosImage_ResultBody()
        {
        }
        
        public GetPosImage_ResultBody(bool return_value, string imageBase64String)
        {
            this.return_value = return_value;
            this.imageBase64String = imageBase64String;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPosHtml
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosHtml", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.GetPosHtmlBody Body;
        
        public GetPosHtml()
        {
        }
        
        public GetPosHtml(NAVAccess.GetPosHtmlBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class GetPosHtmlBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recordID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int fieldNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string html;
        
        public GetPosHtmlBody()
        {
        }
        
        public GetPosHtmlBody(string recordID, int fieldNo, string html)
        {
            this.recordID = recordID;
            this.fieldNo = fieldNo;
            this.html = html;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPosHtml_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosHtml_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.GetPosHtml_ResultBody Body;
        
        public GetPosHtml_Result()
        {
        }
        
        public GetPosHtml_Result(NAVAccess.GetPosHtml_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class GetPosHtml_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool return_value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string html;
        
        public GetPosHtml_ResultBody()
        {
        }
        
        public GetPosHtml_ResultBody(bool return_value, string html)
        {
            this.return_value = return_value;
            this.html = html;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsOnline", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", IsWrapped=true)]
    public partial class IsOnline
    {
        
        public IsOnline()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsOnline_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", IsWrapped=true)]
    public partial class IsOnline_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public bool return_value;
        
        public IsOnline_Result()
        {
        }
        
        public IsOnline_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillDataSet
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillDataSet", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.FillDataSetBody Body;
        
        public FillDataSet()
        {
        }
        
        public FillDataSet(NAVAccess.FillDataSetBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class FillDataSetBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pDataTableID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pDataSetXml;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool pUnformatted;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pStartRow;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pDataRows;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool pIncludeRecIDs;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool pSingleDBRow;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string pErrorText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string pContextInfo;
        
        public FillDataSetBody()
        {
        }
        
        public FillDataSetBody(string pDataTableID, string pDataSetXml, bool pUnformatted, int pStartRow, int pDataRows, bool pIncludeRecIDs, bool pSingleDBRow, string pErrorText, string pContextInfo)
        {
            this.pDataTableID = pDataTableID;
            this.pDataSetXml = pDataSetXml;
            this.pUnformatted = pUnformatted;
            this.pStartRow = pStartRow;
            this.pDataRows = pDataRows;
            this.pIncludeRecIDs = pIncludeRecIDs;
            this.pSingleDBRow = pSingleDBRow;
            this.pErrorText = pErrorText;
            this.pContextInfo = pContextInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillDataSet_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillDataSet_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.FillDataSet_ResultBody Body;
        
        public FillDataSet_Result()
        {
        }
        
        public FillDataSet_Result(NAVAccess.FillDataSet_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class FillDataSet_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool return_value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pDataSetXml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pErrorText;
        
        public FillDataSet_ResultBody()
        {
        }
        
        public FillDataSet_ResultBody(bool return_value, string pDataSetXml, string pErrorText)
        {
            this.return_value = return_value;
            this.pDataSetXml = pDataSetXml;
            this.pErrorText = pErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Find
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Find", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.FindBody Body;
        
        public Find()
        {
        }
        
        public Find(NAVAccess.FindBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class FindBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pDataTableID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pDataSetXml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pFindText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pRowIndex;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pErrorText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pContextInfo;
        
        public FindBody()
        {
        }
        
        public FindBody(string pDataTableID, string pDataSetXml, string pFindText, int pRowIndex, string pErrorText, string pContextInfo)
        {
            this.pDataTableID = pDataTableID;
            this.pDataSetXml = pDataSetXml;
            this.pFindText = pFindText;
            this.pRowIndex = pRowIndex;
            this.pErrorText = pErrorText;
            this.pContextInfo = pContextInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Find_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Find_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.Find_ResultBody Body;
        
        public Find_Result()
        {
        }
        
        public Find_Result(NAVAccess.Find_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class Find_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pRowIndex;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pErrorText;
        
        public Find_ResultBody()
        {
        }
        
        public Find_ResultBody(int pRowIndex, string pErrorText)
        {
            this.pRowIndex = pRowIndex;
            this.pErrorText = pErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRecordZoomData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateRecordZoomData", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.CreateRecordZoomDataBody Body;
        
        public CreateRecordZoomData()
        {
        }
        
        public CreateRecordZoomData(NAVAccess.CreateRecordZoomDataBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class CreateRecordZoomDataBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pDataTableID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pTagFilter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pRecordIDText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pDataSetXml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pErrorText;
        
        public CreateRecordZoomDataBody()
        {
        }
        
        public CreateRecordZoomDataBody(string pDataTableID, string pTagFilter, string pRecordIDText, string pDataSetXml, string pErrorText)
        {
            this.pDataTableID = pDataTableID;
            this.pTagFilter = pTagFilter;
            this.pRecordIDText = pRecordIDText;
            this.pDataSetXml = pDataSetXml;
            this.pErrorText = pErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRecordZoomData_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateRecordZoomData_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.CreateRecordZoomData_ResultBody Body;
        
        public CreateRecordZoomData_Result()
        {
        }
        
        public CreateRecordZoomData_Result(NAVAccess.CreateRecordZoomData_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class CreateRecordZoomData_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pDataSetXml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pErrorText;
        
        public CreateRecordZoomData_ResultBody()
        {
        }
        
        public CreateRecordZoomData_ResultBody(string pDataSetXml, string pErrorText)
        {
            this.pDataSetXml = pDataSetXml;
            this.pErrorText = pErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateRecordZoomInput
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateRecordZoomInput", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.ValidateRecordZoomInputBody Body;
        
        public ValidateRecordZoomInput()
        {
        }
        
        public ValidateRecordZoomInput(NAVAccess.ValidateRecordZoomInputBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class ValidateRecordZoomInputBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pFieldNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pFieldType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pFieldValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pRecDataSet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pZoomDataSet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pErrorText;
        
        public ValidateRecordZoomInputBody()
        {
        }
        
        public ValidateRecordZoomInputBody(int pFieldNo, int pFieldType, string pFieldValue, string pRecDataSet, string pZoomDataSet, string pErrorText)
        {
            this.pFieldNo = pFieldNo;
            this.pFieldType = pFieldType;
            this.pFieldValue = pFieldValue;
            this.pRecDataSet = pRecDataSet;
            this.pZoomDataSet = pZoomDataSet;
            this.pErrorText = pErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateRecordZoomInput_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateRecordZoomInput_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.ValidateRecordZoomInput_ResultBody Body;
        
        public ValidateRecordZoomInput_Result()
        {
        }
        
        public ValidateRecordZoomInput_Result(NAVAccess.ValidateRecordZoomInput_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class ValidateRecordZoomInput_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pZoomDataSet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pErrorText;
        
        public ValidateRecordZoomInput_ResultBody()
        {
        }
        
        public ValidateRecordZoomInput_ResultBody(string pZoomDataSet, string pErrorText)
        {
            this.pZoomDataSet = pZoomDataSet;
            this.pErrorText = pErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportRecordZoomData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportRecordZoomData", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.ImportRecordZoomDataBody Body;
        
        public ImportRecordZoomData()
        {
        }
        
        public ImportRecordZoomData(NAVAccess.ImportRecordZoomDataBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class ImportRecordZoomDataBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pRecordIDText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pRecordZoomDataSet;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool pCallModifyTrigger;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pErrorText;
        
        public ImportRecordZoomDataBody()
        {
        }
        
        public ImportRecordZoomDataBody(string pRecordIDText, string pRecordZoomDataSet, bool pCallModifyTrigger, string pErrorText)
        {
            this.pRecordIDText = pRecordIDText;
            this.pRecordZoomDataSet = pRecordZoomDataSet;
            this.pCallModifyTrigger = pCallModifyTrigger;
            this.pErrorText = pErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportRecordZoomData_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportRecordZoomData_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.ImportRecordZoomData_ResultBody Body;
        
        public ImportRecordZoomData_Result()
        {
        }
        
        public ImportRecordZoomData_Result(NAVAccess.ImportRecordZoomData_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class ImportRecordZoomData_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pErrorText;
        
        public ImportRecordZoomData_ResultBody()
        {
        }
        
        public ImportRecordZoomData_ResultBody(string pErrorText)
        {
            this.pErrorText = pErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRecord
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertRecord", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.InsertRecordBody Body;
        
        public InsertRecord()
        {
        }
        
        public InsertRecord(NAVAccess.InsertRecordBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class InsertRecordBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pDataTableID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pPKey1Data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pPKey2Data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pPKey3Data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pPKey4Data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pPKey5Data;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool pCallInsertTrigger;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string pCreatedRecordID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string pErrorText;
        
        public InsertRecordBody()
        {
        }
        
        public InsertRecordBody(string pDataTableID, string pPKey1Data, string pPKey2Data, string pPKey3Data, string pPKey4Data, string pPKey5Data, bool pCallInsertTrigger, string pCreatedRecordID, string pErrorText)
        {
            this.pDataTableID = pDataTableID;
            this.pPKey1Data = pPKey1Data;
            this.pPKey2Data = pPKey2Data;
            this.pPKey3Data = pPKey3Data;
            this.pPKey4Data = pPKey4Data;
            this.pPKey5Data = pPKey5Data;
            this.pCallInsertTrigger = pCallInsertTrigger;
            this.pCreatedRecordID = pCreatedRecordID;
            this.pErrorText = pErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRecord_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertRecord_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.InsertRecord_ResultBody Body;
        
        public InsertRecord_Result()
        {
        }
        
        public InsertRecord_Result(NAVAccess.InsertRecord_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class InsertRecord_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pCreatedRecordID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pErrorText;
        
        public InsertRecord_ResultBody()
        {
        }
        
        public InsertRecord_ResultBody(string pCreatedRecordID, string pErrorText)
        {
            this.pCreatedRecordID = pCreatedRecordID;
            this.pErrorText = pErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRecord
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteRecord", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.DeleteRecordBody Body;
        
        public DeleteRecord()
        {
        }
        
        public DeleteRecord(NAVAccess.DeleteRecordBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class DeleteRecordBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pDataTableID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pRecordIDText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool pCallDeleteTrigger;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pErrorText;
        
        public DeleteRecordBody()
        {
        }
        
        public DeleteRecordBody(string pDataTableID, string pRecordIDText, bool pCallDeleteTrigger, string pErrorText)
        {
            this.pDataTableID = pDataTableID;
            this.pRecordIDText = pRecordIDText;
            this.pCallDeleteTrigger = pCallDeleteTrigger;
            this.pErrorText = pErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRecord_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteRecord_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.DeleteRecord_ResultBody Body;
        
        public DeleteRecord_Result()
        {
        }
        
        public DeleteRecord_Result(NAVAccess.DeleteRecord_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class DeleteRecord_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pErrorText;
        
        public DeleteRecord_ResultBody()
        {
        }
        
        public DeleteRecord_ResultBody(string pErrorText)
        {
            this.pErrorText = pErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WriteRequestLog", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", IsWrapped=true)]
    public partial class WriteRequestLog
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public string pRequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=1)]
        public System.DateTime pStartDateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=2)]
        public bool pProcessError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=3)]
        public string pErrorText;
        
        public WriteRequestLog()
        {
        }
        
        public WriteRequestLog(string pRequestID, System.DateTime pStartDateTime, bool pProcessError, string pErrorText)
        {
            this.pRequestID = pRequestID;
            this.pStartDateTime = pStartDateTime;
            this.pProcessError = pProcessError;
            this.pErrorText = pErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WriteRequestLog_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", IsWrapped=true)]
    public partial class WriteRequestLog_Result
    {
        
        public WriteRequestLog_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Search
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.SearchBody Body;
        
        public Search()
        {
        }
        
        public Search(NAVAccess.SearchBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class SearchBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pStore;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pTerminal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pContext;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pSearchText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pFilterText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pSearchResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pMaxResults;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int pPageNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool pWild;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool pFuzzy;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string pErrorText;
        
        public SearchBody()
        {
        }
        
        public SearchBody(string pStore, string pTerminal, string pContext, string pSearchText, string pFilterText, string pSearchResult, int pMaxResults, int pPageNo, bool pWild, bool pFuzzy, string pErrorText)
        {
            this.pStore = pStore;
            this.pTerminal = pTerminal;
            this.pContext = pContext;
            this.pSearchText = pSearchText;
            this.pFilterText = pFilterText;
            this.pSearchResult = pSearchResult;
            this.pMaxResults = pMaxResults;
            this.pPageNo = pPageNo;
            this.pWild = pWild;
            this.pFuzzy = pFuzzy;
            this.pErrorText = pErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Search_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices", Order=0)]
        public NAVAccess.Search_ResultBody Body;
        
        public Search_Result()
        {
        }
        
        public Search_Result(NAVAccess.Search_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RetailWebServices")]
    public partial class Search_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pContext;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pSearchResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pErrorText;
        
        public Search_ResultBody()
        {
        }
        
        public Search_ResultBody(string pContext, string pSearchResult, string pErrorText)
        {
            this.pContext = pContext;
            this.pSearchResult = pSearchResult;
            this.pErrorText = pErrorText;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface RetailWebServices_PortChannel : NAVAccess.RetailWebServices_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class RetailWebServices_PortClient : System.ServiceModel.ClientBase<NAVAccess.RetailWebServices_Port>, NAVAccess.RetailWebServices_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RetailWebServices_PortClient() : 
                base(RetailWebServices_PortClient.GetDefaultBinding(), RetailWebServices_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RetailWebServices_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RetailWebServices_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(RetailWebServices_PortClient.GetBindingForEndpoint(endpointConfiguration), RetailWebServices_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RetailWebServices_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RetailWebServices_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RetailWebServices_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RetailWebServices_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RetailWebServices_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVAccess.WebRequest_Result> NAVAccess.RetailWebServices_Port.WebRequestAsync(NAVAccess.WebRequest request)
        {
            return base.Channel.WebRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVAccess.WebRequest_Result> WebRequestAsync(string pxmlRequest, string pxmlResponse)
        {
            NAVAccess.WebRequest inValue = new NAVAccess.WebRequest();
            inValue.Body = new NAVAccess.WebRequestBody();
            inValue.Body.pxmlRequest = pxmlRequest;
            inValue.Body.pxmlResponse = pxmlResponse;
            return ((NAVAccess.RetailWebServices_Port)(this)).WebRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVAccess.CreateResponseCode_Result> NAVAccess.RetailWebServices_Port.CreateResponseCodeAsync(NAVAccess.CreateResponseCode request)
        {
            return base.Channel.CreateResponseCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVAccess.CreateResponseCode_Result> CreateResponseCodeAsync(string pResponse_Code, string pResponse_Text)
        {
            NAVAccess.CreateResponseCode inValue = new NAVAccess.CreateResponseCode();
            inValue.Body = new NAVAccess.CreateResponseCodeBody();
            inValue.Body.pResponse_Code = pResponse_Code;
            inValue.Body.pResponse_Text = pResponse_Text;
            return ((NAVAccess.RetailWebServices_Port)(this)).CreateResponseCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVAccess.GetPosImage_Result> NAVAccess.RetailWebServices_Port.GetPosImageAsync(NAVAccess.GetPosImage request)
        {
            return base.Channel.GetPosImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVAccess.GetPosImage_Result> GetPosImageAsync(string recordID, int fieldNo, string imageBase64String)
        {
            NAVAccess.GetPosImage inValue = new NAVAccess.GetPosImage();
            inValue.Body = new NAVAccess.GetPosImageBody();
            inValue.Body.recordID = recordID;
            inValue.Body.fieldNo = fieldNo;
            inValue.Body.imageBase64String = imageBase64String;
            return ((NAVAccess.RetailWebServices_Port)(this)).GetPosImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVAccess.GetPosHtml_Result> NAVAccess.RetailWebServices_Port.GetPosHtmlAsync(NAVAccess.GetPosHtml request)
        {
            return base.Channel.GetPosHtmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVAccess.GetPosHtml_Result> GetPosHtmlAsync(string recordID, int fieldNo, string html)
        {
            NAVAccess.GetPosHtml inValue = new NAVAccess.GetPosHtml();
            inValue.Body = new NAVAccess.GetPosHtmlBody();
            inValue.Body.recordID = recordID;
            inValue.Body.fieldNo = fieldNo;
            inValue.Body.html = html;
            return ((NAVAccess.RetailWebServices_Port)(this)).GetPosHtmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVAccess.IsOnline_Result> NAVAccess.RetailWebServices_Port.IsOnlineAsync(NAVAccess.IsOnline request)
        {
            return base.Channel.IsOnlineAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVAccess.IsOnline_Result> IsOnlineAsync()
        {
            NAVAccess.IsOnline inValue = new NAVAccess.IsOnline();
            return ((NAVAccess.RetailWebServices_Port)(this)).IsOnlineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVAccess.FillDataSet_Result> NAVAccess.RetailWebServices_Port.FillDataSetAsync(NAVAccess.FillDataSet request)
        {
            return base.Channel.FillDataSetAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVAccess.FillDataSet_Result> FillDataSetAsync(string pDataTableID, string pDataSetXml, bool pUnformatted, int pStartRow, int pDataRows, bool pIncludeRecIDs, bool pSingleDBRow, string pErrorText, string pContextInfo)
        {
            NAVAccess.FillDataSet inValue = new NAVAccess.FillDataSet();
            inValue.Body = new NAVAccess.FillDataSetBody();
            inValue.Body.pDataTableID = pDataTableID;
            inValue.Body.pDataSetXml = pDataSetXml;
            inValue.Body.pUnformatted = pUnformatted;
            inValue.Body.pStartRow = pStartRow;
            inValue.Body.pDataRows = pDataRows;
            inValue.Body.pIncludeRecIDs = pIncludeRecIDs;
            inValue.Body.pSingleDBRow = pSingleDBRow;
            inValue.Body.pErrorText = pErrorText;
            inValue.Body.pContextInfo = pContextInfo;
            return ((NAVAccess.RetailWebServices_Port)(this)).FillDataSetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVAccess.Find_Result> NAVAccess.RetailWebServices_Port.FindAsync(NAVAccess.Find request)
        {
            return base.Channel.FindAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVAccess.Find_Result> FindAsync(string pDataTableID, string pDataSetXml, string pFindText, int pRowIndex, string pErrorText, string pContextInfo)
        {
            NAVAccess.Find inValue = new NAVAccess.Find();
            inValue.Body = new NAVAccess.FindBody();
            inValue.Body.pDataTableID = pDataTableID;
            inValue.Body.pDataSetXml = pDataSetXml;
            inValue.Body.pFindText = pFindText;
            inValue.Body.pRowIndex = pRowIndex;
            inValue.Body.pErrorText = pErrorText;
            inValue.Body.pContextInfo = pContextInfo;
            return ((NAVAccess.RetailWebServices_Port)(this)).FindAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVAccess.CreateRecordZoomData_Result> NAVAccess.RetailWebServices_Port.CreateRecordZoomDataAsync(NAVAccess.CreateRecordZoomData request)
        {
            return base.Channel.CreateRecordZoomDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVAccess.CreateRecordZoomData_Result> CreateRecordZoomDataAsync(string pDataTableID, string pTagFilter, string pRecordIDText, string pDataSetXml, string pErrorText)
        {
            NAVAccess.CreateRecordZoomData inValue = new NAVAccess.CreateRecordZoomData();
            inValue.Body = new NAVAccess.CreateRecordZoomDataBody();
            inValue.Body.pDataTableID = pDataTableID;
            inValue.Body.pTagFilter = pTagFilter;
            inValue.Body.pRecordIDText = pRecordIDText;
            inValue.Body.pDataSetXml = pDataSetXml;
            inValue.Body.pErrorText = pErrorText;
            return ((NAVAccess.RetailWebServices_Port)(this)).CreateRecordZoomDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVAccess.ValidateRecordZoomInput_Result> NAVAccess.RetailWebServices_Port.ValidateRecordZoomInputAsync(NAVAccess.ValidateRecordZoomInput request)
        {
            return base.Channel.ValidateRecordZoomInputAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVAccess.ValidateRecordZoomInput_Result> ValidateRecordZoomInputAsync(int pFieldNo, int pFieldType, string pFieldValue, string pRecDataSet, string pZoomDataSet, string pErrorText)
        {
            NAVAccess.ValidateRecordZoomInput inValue = new NAVAccess.ValidateRecordZoomInput();
            inValue.Body = new NAVAccess.ValidateRecordZoomInputBody();
            inValue.Body.pFieldNo = pFieldNo;
            inValue.Body.pFieldType = pFieldType;
            inValue.Body.pFieldValue = pFieldValue;
            inValue.Body.pRecDataSet = pRecDataSet;
            inValue.Body.pZoomDataSet = pZoomDataSet;
            inValue.Body.pErrorText = pErrorText;
            return ((NAVAccess.RetailWebServices_Port)(this)).ValidateRecordZoomInputAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVAccess.ImportRecordZoomData_Result> NAVAccess.RetailWebServices_Port.ImportRecordZoomDataAsync(NAVAccess.ImportRecordZoomData request)
        {
            return base.Channel.ImportRecordZoomDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVAccess.ImportRecordZoomData_Result> ImportRecordZoomDataAsync(string pRecordIDText, string pRecordZoomDataSet, bool pCallModifyTrigger, string pErrorText)
        {
            NAVAccess.ImportRecordZoomData inValue = new NAVAccess.ImportRecordZoomData();
            inValue.Body = new NAVAccess.ImportRecordZoomDataBody();
            inValue.Body.pRecordIDText = pRecordIDText;
            inValue.Body.pRecordZoomDataSet = pRecordZoomDataSet;
            inValue.Body.pCallModifyTrigger = pCallModifyTrigger;
            inValue.Body.pErrorText = pErrorText;
            return ((NAVAccess.RetailWebServices_Port)(this)).ImportRecordZoomDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVAccess.InsertRecord_Result> NAVAccess.RetailWebServices_Port.InsertRecordAsync(NAVAccess.InsertRecord request)
        {
            return base.Channel.InsertRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVAccess.InsertRecord_Result> InsertRecordAsync(string pDataTableID, string pPKey1Data, string pPKey2Data, string pPKey3Data, string pPKey4Data, string pPKey5Data, bool pCallInsertTrigger, string pCreatedRecordID, string pErrorText)
        {
            NAVAccess.InsertRecord inValue = new NAVAccess.InsertRecord();
            inValue.Body = new NAVAccess.InsertRecordBody();
            inValue.Body.pDataTableID = pDataTableID;
            inValue.Body.pPKey1Data = pPKey1Data;
            inValue.Body.pPKey2Data = pPKey2Data;
            inValue.Body.pPKey3Data = pPKey3Data;
            inValue.Body.pPKey4Data = pPKey4Data;
            inValue.Body.pPKey5Data = pPKey5Data;
            inValue.Body.pCallInsertTrigger = pCallInsertTrigger;
            inValue.Body.pCreatedRecordID = pCreatedRecordID;
            inValue.Body.pErrorText = pErrorText;
            return ((NAVAccess.RetailWebServices_Port)(this)).InsertRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVAccess.DeleteRecord_Result> NAVAccess.RetailWebServices_Port.DeleteRecordAsync(NAVAccess.DeleteRecord request)
        {
            return base.Channel.DeleteRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVAccess.DeleteRecord_Result> DeleteRecordAsync(string pDataTableID, string pRecordIDText, bool pCallDeleteTrigger, string pErrorText)
        {
            NAVAccess.DeleteRecord inValue = new NAVAccess.DeleteRecord();
            inValue.Body = new NAVAccess.DeleteRecordBody();
            inValue.Body.pDataTableID = pDataTableID;
            inValue.Body.pRecordIDText = pRecordIDText;
            inValue.Body.pCallDeleteTrigger = pCallDeleteTrigger;
            inValue.Body.pErrorText = pErrorText;
            return ((NAVAccess.RetailWebServices_Port)(this)).DeleteRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVAccess.WriteRequestLog_Result> NAVAccess.RetailWebServices_Port.WriteRequestLogAsync(NAVAccess.WriteRequestLog request)
        {
            return base.Channel.WriteRequestLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVAccess.WriteRequestLog_Result> WriteRequestLogAsync(string pRequestID, System.DateTime pStartDateTime, bool pProcessError, string pErrorText)
        {
            NAVAccess.WriteRequestLog inValue = new NAVAccess.WriteRequestLog();
            inValue.pRequestID = pRequestID;
            inValue.pStartDateTime = pStartDateTime;
            inValue.pProcessError = pProcessError;
            inValue.pErrorText = pErrorText;
            return ((NAVAccess.RetailWebServices_Port)(this)).WriteRequestLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVAccess.Search_Result> NAVAccess.RetailWebServices_Port.SearchAsync(NAVAccess.Search request)
        {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVAccess.Search_Result> SearchAsync(string pStore, string pTerminal, string pContext, string pSearchText, string pFilterText, string pSearchResult, int pMaxResults, int pPageNo, bool pWild, bool pFuzzy, string pErrorText)
        {
            NAVAccess.Search inValue = new NAVAccess.Search();
            inValue.Body = new NAVAccess.SearchBody();
            inValue.Body.pStore = pStore;
            inValue.Body.pTerminal = pTerminal;
            inValue.Body.pContext = pContext;
            inValue.Body.pSearchText = pSearchText;
            inValue.Body.pFilterText = pFilterText;
            inValue.Body.pSearchResult = pSearchResult;
            inValue.Body.pMaxResults = pMaxResults;
            inValue.Body.pPageNo = pPageNo;
            inValue.Body.pWild = pWild;
            inValue.Body.pFuzzy = pFuzzy;
            inValue.Body.pErrorText = pErrorText;
            return ((NAVAccess.RetailWebServices_Port)(this)).SearchAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RetailWebServices_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RetailWebServices_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://home.tenging.is:9257/IV-HQ-D2-92/WS/Retailing Enterprises, LLC/Codeunit/Re" +
                        "tailWebServices");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RetailWebServices_PortClient.GetBindingForEndpoint(EndpointConfiguration.RetailWebServices_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RetailWebServices_PortClient.GetEndpointAddress(EndpointConfiguration.RetailWebServices_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            RetailWebServices_Port,
        }
    }
}
